pipeline {
    agent any
    triggers {
        cron('H 15 * * *')
    }    
    environment {
        TFPROJECTFOLDER = 'terraform-demo'
    }
    stages {      
      
        stage('Terraform destroy') {
            steps {
                sh '''#!/bin/bash
                cd ${TF_WORKSPACE_PATH}/${TFPROJECTFOLDER};
                terraform destroy -auto-approve;
                '''
            }
        }
        
    }
}
